import Head from 'next/head'
import { Inter } from 'next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useEffect, useState} from 'react';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Ashwin Ranganath | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cv.png" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-300'>developedbyar</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-gray-300'></BsFillMoonStarsFill>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='lg:flex gap-10'>
            <div>
              <div className='text-center p-5 lg:text-left'>
                <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl;'>Ashwin Ranganath</h2>
                <h3 className='text-2xl py-2 md:text- dark:text-gray-300'>Full Stack Web Developer</h3>
                <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>As a full stack web developer, I have experience working with both front-end and back-end technologies, including programming languages such as HTML, JavaScript, CSS, and React.</p>
              </div>
              <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300'>
                <AiFillTwitterCircle></AiFillTwitterCircle>
                <AiFillLinkedin/>
              </div>
            </div>
            <div>
              <div className='relative mx-auto bg-gradient-to-b from-teal-500  rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 lg:mt-0'>
                <Image src={'/ashwin.jpg'} layout='fill' objectFit='cover'  alt={''} />
              </div>
            </div>
          </div>
          

          <div className='transition-colors duration-200 text-center'>
            <div>
              <h3 className='text-3xl py-1 dark:text-gray-300 mt-10'> Services I offer</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                Another Random text
              </p>
            </div>
            <div className='lg:flex gap-10 lg:text-center lg:justify-center '>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:shadow-gray-700'>
                <h3 className='text-lg font-medium pt-8 pb-2 '>Beautiful Designs</h3>
                <p className='py-2'>Some text about deigns</p>
                <h4 className='py-4 text-teal-600'> Design tools I use </h4>
                <p>Photoshop</p>
                <p className='text-gray-800 py-1'>Illustrator</p>
                <p>Figma</p>
                <p>Canva</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:shadow-gray-700'>
                {/* <Image src={design} height={90} width={90}  alt='' /> */}
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2'>Some text about deigns</p>
                <h4 className='py-4 text-teal-600'> Design tools I use </h4>
                <p>Photoshop</p>
                <p className='text-gray-800 py-1'>Illustrator</p>
                <p>Figma</p>
                <p>Canva</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:shadow-gray-700'>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2'>Some text about deigns</p>
                <h4 className='py-4 text-teal-600'> Design tools I use </h4>
                <p>Photoshop</p>
                <p className='text-gray-800 py-1'>Illustrator</p>
                <p>Figma</p>
                <p>Canva</p>
              </div>
            </div>
          </div>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-300'>
              Portfolio
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-300'>
              Some text
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} alt='' className='rounded-lg object-cover' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} alt='' className='rounded-lg object-cover' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} alt='' className='rounded-lg object-cover w-full' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} alt='' className='rounded-lg object-cover w-full' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} alt='' className='rounded-lg object-cover w-full' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} alt='' className='rounded-lg object-cover w-full' layout='responsive'/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
